spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5435/event_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  cache:
    cache-names: [ events ]
    redis:
      host-name: localhost
      port: 6379
      time-to-live: 3600s
      cache-config:
        events:
          ttl: 10800
  kafka:
    bootstrap-servers:
      - kafka1:9092
      - kafka2:9093
    consumer:
      group-id: ticket-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      concurrency: 3
    topic:
      name: ticket-activity

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndTripleDES

application:
  title: Event Service
  version: 1.0

server:
  port: 9001