spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/event_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  title: Event Service
  version: 1.0

server:
  port: 9001