spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/event_db
    username: postgres
    password: ENC(u2w5r7jsreXcrKIdbuqI183na97Rx2Z1)
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  cache:
    cache-names: [ events ]
    redis:
      host-name: localhost
      port: 6379
      time-to-live: 3600s
      cache-config:
        events:
          ttl: 10800
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndTripleDES

application:
  title: Event Service
  version: 1.0

server:
  port: 9001