version: '3.8'
services:
  #  event-service:
  #    build:
  #      context: ../.
  #      dockerfile: Dockerfile
  #    container_name: event-service
  #    ports:
  #        - "9001:9001"
  #    environment:
  #        - SPRING_DATASOURCE_URL=jdbc:postgresql://event-db:5432/event_db
  #        - SPRING_DATASOURCE_USERNAME=postgres
  #        - SPRING_DATASOURCE_PASSWORD=postgres
  #        - SPRING_JPA_HIBERNATE_DDL_AUTO=none
  #        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
  #    depends_on:
  #      - eureka-server
  #      - event-db
  #    networks:
  #        - general

  event-service:
    image: muholo/event-service:latest
    container_name: event-service
    ports:
      - "9001:9001"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://event-db:5432/event_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - event-db
      - redis
    networks:
      - general

  event-db:
    image: 'postgres:13.1-alpine'
    container_name: event-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - general

  eureka-server:
    image: muholo/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - general
    restart: always

  gateway-service:
    image: merttkayaa/gateway-service:latest
    container_name: gateway-service
    ports:
      - "8765:8765"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    restart: always
    networks:
      - general

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:

networks:
  general:
    driver: bridge